fix: PDV 55 add ProvisionedThroughputExceededException handling
pagopa/pdv-ms-tokenizer pull request #26
Opened 2023-05-03 12:50 UTC by BenitoVisone

This PR aim is to handle the `ProvisionedThroughputExceededException` from `DynamoDB` by wrapping it with a Custom `TooManyRequestException`.

The `ProvisionedThroughputExceededException`  is thrown when the Provisioned Capacity is exceeded and the DynamoDB retry policy reaches the end with no results.

2023-05-03 13:07 UTC, rodoviti requested changes

2023-05-03 13:07 UTC, rodoviti commented on connector-api/src/main/java/it/pagopa/pdv/tokenizer/connector/exception/TooManyRequestException.java
> +}
refactor rename `TooManyRequestException` into `TooManyRequestsException` and add the exception cause to constructor like the suggested changes
```suggestion
public class TooManyRequestsException extends RuntimeException {

    public TooManyRequestsException(Throwable cause) {
        super(cause);
    }
}
```

2023-05-03 13:42 UTC, sebbalex approved these changes

2023-05-03 15:16 UTC, rodoviti commented
@BenitoVisone you can avoid code duplication by implementing "exception mapping" using an aspect (AOP) 😉

2023-05-03 15:20 UTC, rodoviti requested changes

2023-05-03 15:20 UTC, rodoviti commented on connector/dao/src/main/java/it/pagopa/pdv/tokenizer/connector/dao/TokenizerConnectorImpl.java
> +            throw new TooManyRequestsException(e.getCause());
you have to set the "current" exception as the cause of the new exception (do this to all refs)
```suggestion
            throw new TooManyRequestsException(e);
```

2023-05-03 15:50 UTC, rodoviti approved these changes
LGTM

PS: if you want to avoid code duplication you can use an aspect (AOP)

2023-05-03 15:54 UTC, BenitoVisone commented
> PS: if you want to avoid code duplication you can use an aspect (AOP)

okay I'll try to substitute this behaviour using AOP, thank you 👍

2023-05-04 13:16 UTC, rodoviti commented on connector/dao/src/main/java/it/pagopa/pdv/tokenizer/connector/dao/handler/ConnectorExceptionHandlingAspect.java
> +    @AfterThrowing(pointcut = "execution(* it.pagopa.pdv.tokenizer.connector.dao.*.*(..))", throwing = "ex")
I suggest narrowing the focus of this advice to Connetor implementation(s) only, but i'm not sure the suggest code is correct.....give it a try 😉 
```suggestion
    @AfterThrowing(pointcut = "execution(public it.pagopa.pdv.tokenizer.connector.dao.*(..))", throwing = "ex")
```

2023-05-17 09:02 UTC, merged